name: hawa_v1
description: "Women safety application"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  shared_preferences: ^2.2.3
  smooth_page_indicator : ^1.1.0
  cloud_firestore: ^4.17.5
  google_fonts : ^6.2.1
  url_launcher : ^6.2.6
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  telephony: ^0.2.0
  firebase_storage: ^11.7.7
  firebase_app_check: ^0.2.2+7
  sensors_plus: ^5.0.1
  location: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl : ^0.19.0
  flutter_launcher_icons : ^0.13.1
  logger : ^2.3.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/hawa_background.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/hawa_logo.png
    - assets/images/location_onboard.png
    - assets/images/snap_onboard.png
    - assets/images/emergency_onboard.png
    - assets/images/nextArrow.png
    - assets/images/backArrow.png
    - assets/images/hawa_name.png
    - assets/images/natalia.png
    - assets/images/illaila.png
    - assets/images/afiqah.png
    - assets/images/aliah.png
    - assets/images/SOS.png
    - assets/images/google_logo.png
  fonts:
    - family : Roboto
      fonts:
        - asset : assets/fonts/Roboto-Bold.ttf
          weight : 700
        - asset : assets/fonts/Roboto-Light.ttf
          weight : 300
        - asset : assets/fonts/roboto-Regular.ttf
          weight : 400
